name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O la rama principal de tu repositorio (ej. master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # ¡NUEVA SECCIÓN DE PERMISOS!
    permissions:
      contents: write # Permite que el workflow escriba en el repositorio (para crear/actualizar la rama gh-pages)
      pages: write # Permite al workflow interactuar con la API de Pages (requerido para despliegues de Pages)
      id-token: write # Necesario para la autenticación en OIDC, que algunas acciones de Pages podrían usar internamente

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
