name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O la rama principal de tu repositorio (ej. master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm npm run build # ¡Asegúrate de que este comando sea 'npm run build', no 'npm npm run build'!

      # ¡NUEVO PASO! Crear el archivo .nojekyll
      - name: Create .nojekyll file
        run: touch ./docs/.nojekyll # Crea un archivo vacío en el directorio de publicación

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
